from numba import njit
import numpy as np
import glm
import math

MAJOR_VER, MINOR_VER = 3, 3
DEPTH_SIZE = 24
NUM_SAMPLES = 1 

WIN_RES = glm.vec2(1600, 900)
MAX_FPS = 120

SEED = 16

MAX_RAY_DIST = 6

CHUNK_SIZE = 48
H_CHUNK_SIZE = CHUNK_SIZE // 2
CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE
CHUNK_VOL = CHUNK_AREA * CHUNK_SIZE
CHUNK_SPHERE_RADIUS = H_CHUNK_SIZE * math.sqrt(3)

WORLD_W, WORLD_H = 20, 2
WORLD_D = WORLD_W
WORLD_AREA = WORLD_W * WORLD_D
WORLD_VOL = WORLD_AREA * WORLD_H
CHUNK_RENDER_RADIUS = 8

CENTER_XZ = WORLD_W * H_CHUNK_SIZE
CENTER_Y = WORLD_H * H_CHUNK_SIZE

ASPECT_RATIO = WIN_RES.x / WIN_RES.y
FOV_DEG = 50
V_FOV = glm.radians(FOV_DEG)  
H_FOV = 2 * math.atan(math.tan(V_FOV * 0.5) * ASPECT_RATIO)  
NEAR = 0.1
FAR = 2000.0
PITCH_MAX = glm.radians(89)

PLAYER_SPEED = 5.0
PLAYER_SPRINT_MULT = 1.8
PLAYER_ROT_SPEED = 0.003
WATER_LINE = 5.6
WATER_WALK_MULT = 0.8
WATER_SWIM_MULT = 0.55
WATER_WADE_ASCEND_SPEED = 2.8
WATER_SWIM_ASCEND_SPEED = 4.2
WATER_DIVE_SPEED = -5.5
WATER_WADE_GRAVITY = -1.4
WATER_SWIM_GRAVITY = -0.7
WATER_WADE_TERMINAL = -0.7
WATER_SWIM_TERMINAL = -0.25
WATER_VERTICAL_DRAG = 0.9

WATER_SURFACE_Y = WATER_LINE + 0.02
WATER_UV_SCALE = 0.08
UNDERWATER_FOG_COLOR = glm.vec3(0.15, 0.38, 0.72)
UNDERWATER_FOG_DENSITY = 0.00012

PLAYER_POS = glm.vec3(CENTER_XZ, CHUNK_SIZE, CENTER_XZ)
MOUSE_SENSITIVITY = 0.002

BG_COLOR = glm.vec3(0.58, 0.83, 0.99)
NIGHT_SKY_COLOR = glm.vec3(0.03, 0.05, 0.12)
DAWN_SKY_COLOR = glm.vec3(0.96, 0.54, 0.30)
NIGHT_AMBIENT_LIGHT = 0.28
DAY_AMBIENT_LIGHT = 1.0
DAY_NIGHT_CYCLE_SECONDS = 300.0
DAY_NIGHT_START_OFFSET = 0.5

SAND = 1
GRASS = 2
DIRT = 3
STONE = 4
SNOW = 5
LEAVES = 6
WOOD = 7
ROCK = 8
COAL_ORE = 9
IRON_ORE = 10
BEDROCK = 11
ALT_LEAVES = 12

CHERRY_LEAF_VARIANT_CHANCE = 0.35
CHERRY_ALT_LEAVES_TEXTURE = 'green_leaves.png'

CAVE_SURFACE_BUFFER = 5
CAVE_FREQUENCY = 0.018
CAVE_THRESHOLD = 0.56
CAVE_MOUTH_FREQUENCY = 0.008
CAVE_MOUTH_THRESHOLD = 0.57
CAVE_MOUTH_DEPTH = 22
CAVE_MOUTH_DEPTH_BONUS = 22
CAVE_MOUTH_MOUNTAIN_BONUS = 0.25
CAVE_COVER_THICKNESS = 4
ORE_FREQUENCY = 0.06
ORE_CLUSTER_FREQUENCY = 0.025
ORE_CLUSTER_THRESHOLD = 0.62
ORE_COAL_THRESHOLD = 0.55
ORE_IRON_THRESHOLD = 0.58
ORE_MIN_DEPTH = 8
ORE_CAVE_BONUS = 0.22
ROCK_DEPTH = 11
ROCK_FREQUENCY = 0.04
ROCK_THRESHOLD = 0.74
BEDROCK_LAYER = 0
BASE_ROCK_LAYER = 1
STONE_LVL = 49
DIRT_LVL = 40
SNOW_LVL = 54
GRASS_LVL = 8
SAND_LVL = 7

TREE_PROBABILITY = 0.02
TREE_WIDTH, TREE_HEIGHT = 4, 8
TREE_H_WIDTH, TREE_H_HEIGHT = TREE_WIDTH // 2, TREE_HEIGHT // 2

WATER_AREA = 5 * CHUNK_SIZE * WORLD_W

CLOUD_SCALE = 25
CLOUD_HEIGHT = WORLD_H * CHUNK_SIZE * 2